name: Deploy Itch

on:
  release:
    types: [published]
  workflow_dispatch:
env:
  ITCH_USER: benkeks
  ITCH_GAME: clave
jobs:
  build:
    uses: ./.github/workflows/scala-main-build.yml
  deploy:
    name: Upload to Itch
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/download-artifact@v2.0.8
        with:
          name: clave
          path: build/clave
      - uses: manleydev/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          PACKAGE: build/clave
          VERSION: 0.1.4