name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:
    secrets:
      CI_USER:
        required: true
      CI_PRIVKEY:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Coursier cache
      uses: coursier/cache-action@v6
    - name: Compile game
      run: sbt fullOptJS
    - name: Deploy CI
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: target/scala-2.13/classes/
        remote_path: /www/htdocs/${{ secrets.CI_USER }}/clave.keks.in/
        remote_host: code.keks.in
        remote_user: ssh-${{ secrets.CI_USER }}
        remote_key: ${{ secrets.CI_PRIVKEY }}
    - name: Archive production webclient artifact
      uses: actions/upload-artifact@v3
      with:
        name: clave
        path: |
          target/scala-2.13/classes
    - name: Cleanup before cache
      shell: bash
      run: |
        rm -rf "$HOME/.ivy2/local" || true
        find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                              -name "*.lock"               -delete || true
